---
- name: Update package cache
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install GUI applications
  apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - dunst
    - i3
    - meld
    - rxvt-unicode-256color
    - vim-gtk3
    - xclip

- name: Download Source Sans Pro font
  get_url:
    url: https://github.com/adobe-fonts/source-sans-pro/releases/download/variable-fonts/SourceSansVariable-Roman.otf
    dest: ~/.local/share/fonts
    mode: 0644

- name: Download Source Sans Pro italic font
  get_url:
    url: https://github.com/adobe-fonts/source-sans-pro/releases/download/variable-fonts/SourceSansVariable-Italic.otf
    dest: ~/.local/share/fonts
    mode: 0644

- name: Download Source Code Pro font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.otf
    dest: ~/.local/share/fonts
    mode: 0644

- name: Download Source Code Pro italic font
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Italic.otf
    dest: ~/.local/share/fonts
    mode: 0644

- name: Update fonts cache
  command: fc-cache -f "~/.local/share/fonts"

- name: Install Inconsolata font
  apt: name=fonts-inconsolata state=latest
  become: yes
  become_method: sudo

- name: Install Powerline patched fonts
  apt: name=fonts-powerline state=latest
  become: yes
  become_method: sudo

- name: Clone Paper Icon Theme repository
  git:
    repo: 'https://github.com/snwh/paper-icon-theme.git'
    dest: '~/temp/paper-icon-theme'
    depth: 1

- name: Copy Paper Icon Theme in place
  synchronize:
    src:  '~/temp/paper-icon-theme/Paper'
    dest: '~/.local/share/icons/'
  delegate_to: "{{ inventory_hostname }}"

# keepassxc?
# zeal?
# rofi?

